### ISSUE TITLE
undefined method 'notable_exception_raised'

### ISSUE THREAD

**Issue by chuenlok** [decko-commons/decko#174]
Hi @ethn , @xithan ,

Long time no see :) I haven't had a chance to sneak in your meeting in Vignesh's office so I am greeting you guys here (and raise an issue I encountered)!

I promised Philipp that I will add something to decko but I had a problem while trying to start a new deck. 

I created a new deck with `decko new mysite --core-dev`. I did `decko seed` but when I did `decko server`, I was seeing the error `undefined method 'notable_exception_raised'`.

Here is the backtrace:
```
NoMethodError (undefined method `notable_exception_raised' for #<Card:0x007f8d44fed250>):

activemodel (5.1.5) lib/active_model/attribute_methods.rb:432:in `method_missing'
/Users/navi/dev/decko/decko/card/lib/card/error.rb:77:in `problematic_exception_view'
/Users/navi/dev/decko/decko/card/lib/card/error.rb:71:in `exception_view'
/Users/navi/dev/decko/decko/decko/rails/controllers/card_controller.rb:139:in `block in <class:CardController>'
activesupport (5.1.5) lib/active_support/rescuable.rb:115:in `instance_exec'
activesupport (5.1.5) lib/active_support/rescuable.rb:115:in `block in handler_for_rescue'
activesupport (5.1.5) lib/active_support/rescuable.rb:91:in `rescue_with_handler'
activesupport (5.1.5) lib/active_support/rescuable.rb:164:in `rescue_with_handler'
actionpack (5.1.5) lib/action_controller/metal/rescue.rb:23:in `rescue in process_action'
actionpack (5.1.5) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.1.5) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.1.5) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.5) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.5) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.5) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.1.5) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
activerecord (5.1.5) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
actionpack (5.1.5) lib/abstract_controller/base.rb:124:in `process'
actionview (5.1.5) lib/action_view/rendering.rb:30:in `process'
actionpack (5.1.5) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (5.1.5) lib/action_controller/metal.rb:253:in `dispatch'
actionpack (5.1.5) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (5.1.5) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (5.1.5) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (5.1.5) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.5) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.5) lib/action_dispatch/routing/route_set.rb:844:in `call'
railties (5.1.5) lib/rails/engine.rb:522:in `call'
railties (5.1.5) lib/rails/railtie.rb:185:in `public_send'
railties (5.1.5) lib/rails/railtie.rb:185:in `method_missing'
actionpack (5.1.5) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
actionpack (5.1.5) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.1.5) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (5.1.5) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.5) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.5) lib/action_dispatch/routing/route_set.rb:844:in `call'
rack (2.0.4) lib/rack/etag.rb:25:in `call'
rack (2.0.4) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.4) lib/rack/head.rb:12:in `call'
rack (2.0.4) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.4) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.5) lib/action_dispatch/middleware/cookies.rb:613:in `call'
actionpack (5.1.5) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.5) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.5) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
rails-dev-tweaks (1.2.0) lib/rails_dev_tweaks/granular_autoload/middleware.rb:36:in `call'
actionpack (5.1.5) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
actionpack (5.1.5) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.5) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.5) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.5) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.5) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.5) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.5) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.5) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.5) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.4) lib/rack/method_override.rb:22:in `call'
rack (2.0.4) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.5) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.5) lib/action_dispatch/middleware/executor.rb:12:in `call'
rack (2.0.4) lib/rack/lock.rb:17:in `call'
actionpack (5.1.5) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.4) lib/rack/sendfile.rb:111:in `call'
railties (5.1.5) lib/rails/engine.rb:522:in `call'
thin (1.7.2) lib/thin/connection.rb:86:in `block in pre_process'
thin (1.7.2) lib/thin/connection.rb:84:in `catch'
thin (1.7.2) lib/thin/connection.rb:84:in `pre_process'
thin (1.7.2) lib/thin/connection.rb:53:in `process'
thin (1.7.2) lib/thin/connection.rb:39:in `receive_data'
eventmachine (1.2.5) lib/eventmachine.rb:194:in `run_machine'
eventmachine (1.2.5) lib/eventmachine.rb:194:in `run'
thin (1.7.2) lib/thin/backends/base.rb:73:in `start'
thin (1.7.2) lib/thin/server.rb:162:in `start'
rack (2.0.4) lib/rack/handler/thin.rb:22:in `run'
rack (2.0.4) lib/rack/server.rb:297:in `start'
railties (5.1.5) lib/rails/commands/server/server_command.rb:44:in `start'
railties (5.1.5) lib/rails/commands/server/server_command.rb:135:in `block in perform'
railties (5.1.5) lib/rails/commands/server/server_command.rb:130:in `tap'
railties (5.1.5) lib/rails/commands/server/server_command.rb:130:in `perform'
thor (0.20.0) lib/thor/command.rb:27:in `run'
thor (0.20.0) lib/thor/invocation.rb:126:in `invoke_command'
thor (0.20.0) lib/thor.rb:387:in `dispatch'
railties (5.1.5) lib/rails/command/base.rb:63:in `perform'
railties (5.1.5) lib/rails/command.rb:44:in `invoke'
railties (5.1.5) lib/rails/commands.rb:16:in `<top (required)>'
/Users/navi/dev/decko/decko/decko/lib/decko/commands.rb:77:in `require'
/Users/navi/dev/decko/decko/decko/lib/decko/commands.rb:77:in `<top (required)>'
script/decko:6:in `require'
script/decko:6:in `<main>'
Started GET "/favicon.ico" for 127.0.0.1 at 2018-02-27 22:38:28 +0000
RailsDevTweaks: Skipping ActionDispatch::Reloader hooks for this request.
Processing by CardController#read as
  Parameters: {"id"=>"favicon"}
exception = NoMethodError: undefined method `[]' for #<Class:0x007f8d41618ed0>
Completed 500 Internal Server Error in 44ms (ActiveRecord: 0.0ms)
```

Please let me know if I am already outdated and need some new command to do the core dev. 

Thank you very much :)

**Comment by ethn** [comment]
Hey Henry!

I can't look at this right away, but I will soon.  If I remember correctly, it's something goofy, like maybe this is the error you get you don't have cards?  I'm wondering if you don't have cards in the right environment and you need to run `decko seed -a` ?

**Comment by chuenlok** [comment]
Thank Ethan! I remember what I missed. I have to init the submodules otherwise the seed will miss all the needed cards!  Thank you very much :)
